mysite/mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'mysite.views.home', name='home'),
    url(r'^contact/', 'contact.views.contact', name='contact'),
    url(r'^photos/', include('photos.urls', namespace='photos')),
    url(r'^polls/', include('polls.urls', namespace='polls')),  # namespace each app in a project
    url(r'^admin/', include(admin.site.urls)),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url('', include('django.contrib.auth.urls', namespace='auth')),
)

# The url() function is passed four arguments, two required: regex and view, and two optional: kwargs, and name.

# When somebody requests a page from your Web site - say, /polls/34/, Django will load the mysite.urls Python module
# because it is pointed to by the ROOT_URLCONF setting.
# It finds the variable named urlpatterns and traverses the regular expressions in order. 
# The include() functions we are using simply reference other URLconfs. 
# Note that the regular expressions for the include() functions do not have a $ (end-of-string match character) but
# rather a trailing slash.
# Whenever Django encounters include(), it chops off whatever part of the URL matched up to that point and sends the
# remaining string to the included URLconf for further processing.

# If a user goes to /polls/34/ in this system:
# Django will find the match at "^polls/""
# Then, Django will strip off the matching text polls/ and send the remaining text - 34/ - to the polls.urls
# URLconf for further processing which matches r"^(?P<question_id>\d+)/$"" resulting in a call to the detail() view
# like so:
# detail(request=<HttpRequest object>, question_id="34")

mysite/polls/urls.py
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'), # ex: /polls/
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'), # ex: /polls/5/
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'), # ex: /polls/5/results/
    url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'), # ex: /polls/5/vote/
    url(r'^question/', 'polls.views.get_question', name='get_question'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='auth_logout'),
    url(r'^logout/(?P<next_page>.*)/$', 'django.contrib.auth.views.logout', name='auth_logout_next'),
)

mysite/polls/models.py
# this poll application is a database Web app
# database layout and metadata is located here

import datetime

from django.db import models
from django.utils import timezone
# Create your models here.

# Question model, which contains a question and a publication date


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):	# __unicode__ on Python 2
        return self.question_text # this method will allow us to print out objects in shell

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now # recent pub_date must be between a day ago and now

    was_published_recently.admin_order_field = 'pub_date' # add support for sorting the output of the was_published_recently column in the Admin/Polls/Questions page
    was_published_recently.boolean = True # adds the check or minus icon for true or false in the was_published_recently column
    was_published_recently.short_description = 'Published recently?"' # replaces the default column header from 'was_published_recently'


# Choice model, which contains two fields: the text of the choice and a vote tally
class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):	 # __unicode__ on Python 2
        results = "choice-%s; votes-%s" % (str(self.choice_text), str(self.votes))
        return results
        #return self.choice_text


# User model
class User(models.Model):
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    def __str__(self):
        pass


# Each of model is represented by a class that subclasses django.db.models.Model
# Each model has a number of class variables, each of which represents a database field in the model.
# Each field is represented by an instance of a Field class, e.g., CharField for character fields and DateTimeField for datetimes. This tells Django what type of data each field holds.
# The name of each Field instance (eg question_text or pub_date) is the field"s name, in machine-friendly format. You will use this value in your Python code, and your database will use it as the column name.
# You can use an optional first positional argument to a Field to designate a human readable name. That"s used in a couple of introspective parts of Django, and it doubles as documentation. If this field is not provided, Django will use the machine-readable name. In this example, we have only defined a human-readable name for Question.pub_date. For all other fields in this model, the field"s machine-readable name will suffice as its human-readable name.
# Some Field classes have required arguments. CharField, for example, requires that you give it a max_length. That is used not only in the database schema, but in validation, as we will soon see 
# A Field can also have various optional arguments; in this case, we have set the default value of votes to 0.
# Finally, note a relationship is defined, using ForeignKey. That tells Django each Choice is related to a single Question. Django supports all the common database relationships: many-to-one, many-to-many and one-to-one.

mysite/polls/forms.py
from django import forms


class QuestionForm(forms.Form):
    your_question = forms.CharField(label='Add a new question', max_length=250)
    your_answer_a = forms.CharField(label="A", max_length=100, min_length=1)
    your_answer_b = forms.CharField(label="B", max_length=100, min_length=1, required=False)
    your_answer_c = forms.CharField(label="C", max_length=100, min_length=1, required=False)
    your_answer_d = forms.CharField(label="D", max_length=100, min_length=1, required=False)
    your_answer_e = forms.CharField(label="E", max_length=100, min_length=1, required=False)

mysite/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import Http404
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.views import generic
#from django.template import RequestContext, loader
from django.shortcuts import render_to_response
from django.template.context import RequestContext

from polls.models import Choice, Question
from polls.forms import QuestionForm

# Create your views here.

# Using two generic views: ListView and DetailView, to display a list of objects and display a detail page for a
# particular type of object respectively


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions.
        """
        return Question.objects.filter( # returns a queryset containing Questions whose pub_date is less than or equal
            # to - that is, earlier than or equal to - timezone.now
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """Excludes any questions that aren't published yet"""
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

    def get_queryset(self):
        """Excludes any questions that aren't published yet"""
        return Question.objects.filter(pub_date__lte=timezone.now())


def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice']) # request.POST['choice'] returns the ID of the
        # selected choice, as a string (note: request.POST values are always strings). Unlike request.GET (which also
        # accesses GET data in the same way), request.POST alters data via a POST call
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
            })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,))) # Redirect to results page.
            # Unlike HttpResponse, HttpResponseRedirect takes a single argument: the URL to which the user will be
            # redirected (see the following point for how we construct the URL in this case). Using the reverse()
            # function helps avoid hacing to hardcode a URL in the view function; it is given the name of the view we
            # want to pass control to and the variable portion of the URL pattern that points to the view Original:
            # return HttpResponse("You're voting on question %s." % question_id)
            # Always return an HttpResponseRedirect after successfully dealing with Post data. This prevents data from
            # being posted twice if a user his the Back button


def get_question(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = QuestionForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            question_body = request.POST.get('your_question', '')
            new_question = Question(question_text=question_body, pub_date=timezone.now())
            new_question.save()

            characters = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w',
                          'x','y','z']
            for i in range(0, 5):
                answer_text = 'your_answer_' + characters[i]
                new_answer = request.POST.get(answer_text, '')
                if new_answer != '':
                    new_choice = Choice(question=new_question, choice_text=new_answer, votes=0)
                    new_choice.save()
            # process the data in form.cleansed_data as required
            # ...
            # redirect to a new URL:
            return HttpResponseRedirect('/polls/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = QuestionForm()

    return render(request, 'polls/question.html', {'form': form})

mysite/polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Mysite With Authentication{% endblock %}</title>

    <!-- Bootstrap -->
    <link href="../../static/polls/css/bootstrap.min.css" rel="stylesheet">
    <link href="../../static/polls/css/bootstrap-theme.min.css" rel="stylesheet">
    {#   <link href="static/css/fbposter.css" rel="stylesheet">#}

    <link href="../../static/polls/css/style.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,800,700,300' rel='stylesheet' type='text/css'>
    <link rel="icon" type="image/png" href="../../static/polls/img/favicon.png">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
     <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
     <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <!-- Navbar -->
	<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	    <div class="container">
	        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
	        </button>
            <a class="navbar-brand text-muted" href="/" title="Return home">My Site Home</a>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="/" title="Return home"><span aria-hidden="true" data-icon="&#xe100;"></span>Home</a></li>
                    <li class="active"><a href="/polls" title="Check out our polls">Polls</a></li>
                    <!-- <span aria-hidden="true" data-icon="&#xe607;"></span> -->
                    <li class="dropdown" id="navPhotos">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="Check out our photos uploader">Photos <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="/photos/uploadfile">Upload Photo</a></li>
                            <li><a href="/photos/listfiles">List Files</a></li>
                        </ul>
                    </li>
                    <li><a href="/contact" title="Contact us">Contact</a></li>
                    <!-- <span aria-hidden="true" data-icon="&#xe620;"></span> -->
                    <li class="dropdown">
                    {% if user and not user.is_anonymous %}
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="Account">{{ user.username }} <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a>Hello {{ user.get_full_name|default:user.username }}!</a>
                            </li>
                            <li>
                                <a href="{% url 'auth:logout' %}?next=/polls">Logout</a>
{#                                <a href="{% url 'auth:logout' %}?next={{ request.path }}">Logout</a>#}
                            </li>
                        </ul>
                    {% else %}
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="Login or Signup">Login <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="{% url 'social:begin' 'facebook' %}?next=/polls">Login with Facebook</a>
                                </li>
                                <li>
                                    <a href="{% url 'social:begin' 'google-oauth2' %}?next=/polls">Login with Google</a>
                                </li>
                                <li>
                                    <a href="{% url 'social:begin' 'twitter' %}?next=/polls">Login with Twitter</a>
                                </li>
                            </ul>
                    {% endif %}
                    </li>
                </ul>
            </div>
        </div>
	</nav>
	<!-- End navbar -->

    <div class="main-content">
        <div>
            <h1>Polls App</h1>
        </div>

        {% block main %}{% endblock %}
    </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="../../static/js/jquery-1.11.1.min.js"></script>
    {#   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>#}
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="../../static/js/bootstrap.min.js"></script>
</body>
</html>

mysite/polls/templates/polls/detail.html
{% extends 'polls/base.html' %}

{#{% load staticfiles %} #}
<!-- load static template page from the staticfiles template library -->

{#<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" /> #}
<!--  static  template tag generates the absolute URL of the static file -->

{% block main %}

    <h2>{{ question.question_text }}</h2>

    {% if error_message %}
        <p style="color:red"><strong>{{ error_message }}</strong></p>
    {% endif %}

    <form action="{% url 'polls:vote' question.id %}" method="post"> <!-- Set the form’s action to ..., and set method="post" (pposed to method="get"), because the act of submitting this form will alter data server-side -->
    {% csrf_token %} <!-- django system for protecting against Cross Site Request Forgeries -->
    {% for choice in question.choice_set.all %} <!-- question.choice_set.all is interpeted as Python code question.choice_set.all() which returns an iterable of Choice objects. The choice_set attribute is from the django api for linked the the related model (Choice) to the model that defines the relationship (Question)-->
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" /> <!-- display a rdio button for each question choice, where the value of each radio button id the associated question choice's ID. The name of each radio button is "choice". That means, when somebody selects one of the radio buttons and submits the form, it’ll send the POST data choice=# where # is the ID of the selected choice. This is the basic concept of HTML forms. -->
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
    {% endfor %}
    <input type="submit" class="btn btn-success" value="Vote" />
    </form>

{% endblock %}

mysite/polls/templates/polls/index.html
<head>
    <title>Polls</title>
</head>

{% extends 'polls/base.html' %}

{#{% load staticfiles %}#}
<!-- load static template page from the staticfiles template library -->

{#<link rel="stylesheet" type="text/css" href="{% static '/../../static/polls/css/style.css' %}" />#}
<!--  static  template tag generates the absolute URL of the static file -->

{% block main %}

    <h2>Poll Questions</h2>
    {% if latest_question_list %}
        <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li> <!-- create a bulleted-list containing of the questions, where each question's link points to the question's detail page. This uses a namespace and is not hardcoded -->
        {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}

    <a href="/polls/question" class="btn btn-primary" role="button">Add a New Poll Question</a>

{% endblock %}

mysite/polls/templates/polls/question.html
<head>
    <title>Add a New Question</title>
</head>

{% extends 'polls/base.html' %}

{#{% load staticfiles %}#}
<!-- load static template page from the staticfiles template library -->

{#<link rel="stylesheet" type="text/css" href="{% static '/../../static/polls/css/style.css' %}" />#}
<!--  static  template tag generates the absolute URL of the static file -->

{% block main %}

<form action="" method="post">{% csrf_token %}
    <div class="field">
        {{ form.your_question.errors }}
        <label for="id_your_question">Question:</label>
        {{ form.your_question }}
    </div>
    <div class="field">
        {{ form.your_answer_a.errors }}
        <label for="id_your_answers_a">A:</label>
        {{ form.your_answer_a }}
    </div>
    <div class="field">
        {{ form.your_answer_b.errors }}
        <label for="id_your_answers_b">B:</label>
        {{ form.your_answer_b }}
    </div>
    <div class="field">
        {{ form.your_answer_c.errors }}
        <label for="id_your_answers_c">C:</label>
        {{ form.your_answer_c }}
    </div>
    <div class="field">
        {{ form.your_answer_d.errors }}
        <label for="id_your_answers_d">D:</label>
        {{ form.your_answer_d }}
    </div>
    <div class="field">
        {{ form.your_answer_e.errors }}
        <label for="id_your_answers_e">E:</label>
        {{ form.your_answer_e }}
    </div>
    <input type="submit" value="Submit" class="btn btn-primary"/>
</form>

{% endblock %}

mysite/polls/templates/polls/results.html
{% extends 'polls/base.html' %}

{#{% load staticfiles %} #}
<!-- load static template page from the staticfiles template library -->

{#<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" /> #}
<!--  static  template tag generates the absolute URL of the static file -->

{% block main %}

    <h2>{{ question.question_text }}</h2>

    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>

    <button><a href="{% url 'polls:detail' question.id %}">Vote again?</a></button>

{% endblock %}