mysite/mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'mysite.views.home', name='home'),
    url(r'^contact/', 'contact.views.contact', name='contact'),
    url(r'^photos/', include('photos.urls', namespace='photos')),
    url(r'^polls/', include('polls.urls', namespace='polls')),  # namespace each app in a project
    url(r'^admin/', include(admin.site.urls)),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url('', include('django.contrib.auth.urls', namespace='auth')),
)

# The url() function is passed four arguments, two required: regex and view, and two optional: kwargs, and name.

# When somebody requests a page from your Web site - say, /polls/34/, Django will load the mysite.urls Python module
# because it is pointed to by the ROOT_URLCONF setting.
# It finds the variable named urlpatterns and traverses the regular expressions in order. 
# The include() functions we are using simply reference other URLconfs. 
# Note that the regular expressions for the include() functions do not have a $ (end-of-string match character) but
# rather a trailing slash.
# Whenever Django encounters include(), it chops off whatever part of the URL matched up to that point and sends the
# remaining string to the included URLconf for further processing.

# If a user goes to /polls/34/ in this system:
# Django will find the match at "^polls/""
# Then, Django will strip off the matching text polls/ and send the remaining text - 34/ - to the polls.urls
# URLconf for further processing which matches r"^(?P<question_id>\d+)/$"" resulting in a call to the detail() view
# like so:
# detail(request=<HttpRequest object>, question_id="34")

mysite/photos/urls.py
from django.conf.urls import patterns, url, static, include
from django.contrib import admin
from django.views.generic import TemplateView

from photos import views

urlpatterns = patterns('',
  url(r'^uploadfile/$', views.upload_photo, name='uploadphoto'),
  url(r'^listfiles/$', views.display_photo, name='displayphoto'),
  url(r'^afterupload/$', TemplateView.as_view(template_name='photos/afterupload.html'), name='afterupload')
)

mysite/polls/urls.py
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'), # ex: /polls/
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'), # ex: /polls/5/
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'), # ex: /polls/5/results/
    url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'), # ex: /polls/5/vote/
    url(r'^question/', 'polls.views.get_question', name='get_question'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='auth_logout'),
    url(r'^logout/(?P<next_page>.*)/$', 'django.contrib.auth.views.logout', name='auth_logout_next'),
)

mysite/photos/models.py
import datetime

from django.db import models


# Create your models here.
class UploadPhoto(models.Model):
    file = models.FileField(upload_to="uploads")

mysite/photos/forms.py
from django import forms
from photos.models import UploadPhoto


class UploadPhotoForm(forms.ModelForm):
    class Meta:
        model = UploadPhoto

mysite/photos/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from .forms import UploadPhotoForm
from photos.models import UploadPhoto


# Create your views here.
def upload_photo(request):
    if request.method == 'POST':
        form = UploadPhotoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return render(request, 'photos/afterupload.html')
    else:
        form = UploadPhotoForm()
    return render(request, 'photos/upload.html', {'form': form})


def display_photo(request):
    image_names = [p.file.name for p in UploadPhoto.objects.all()]
    return render(request, 'photos/listfiles.html', {'names': image_names})

mysite/photos/templates/photos/afterupload.html
{% extends 'photos/base.html' %}

{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'photos/style.css' %}" />

{% block main %}

<section class="desc">
   <p>You've just uploaded a photo!</p>
</section>

<section class="desc" id="links">
   <a href="{% url 'photos:uploadphoto' %}">upload new photo</a>
   </br>
   <a href="{% url 'photos:displayphoto' %}">view gallery</a>
</section>

{% endblock %}

mysite/photos/templates/photos/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Mysite With Authentication{% endblock %}</title>

    <!-- Bootstrap -->
    <link href="../../static/photos/css/bootstrap.min.css" rel="stylesheet">
    <link href="../../static/photos/css/bootstrap-theme.min.css" rel="stylesheet">
    {#   <link href="static/css/fbposter.css" rel="stylesheet">#}

    <link rel="stylesheet" type="text/css" href="{% static 'photos/style.css' %}" />
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,800,700,300' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
     <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
     <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <!-- Navbar -->
	<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	    <div class="container">
	        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
	        </button>
            <a class="navbar-brand text-muted" href="/" title="Return home">My Site Home</a>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="/" title="Return home"><span aria-hidden="true" data-icon="&#xe100;"></span>Home</a></li>
                    <li><a href="/polls" title="Check out our polls">Polls</a></li>
                    <!-- <span aria-hidden="true" data-icon="&#xe607;"></span> -->
                    <li class="dropdown" id="navPhotos">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="Check out our photos uploader">Photos <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="/photos/uploadfile">Upload Photo</a></li>
                            <li><a href="/photos/listfiles">List Files</a></li>
                        </ul>
                    </li>
                    <li><a href="/contact" title="Contact us">Contact</a></li>
                    <!-- <span aria-hidden="true" data-icon="&#xe620;"></span> -->
                    <li class="dropdown">
                    {% if user and not user.is_anonymous %}
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="Account">{{ user.username }} <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a>Hello {{ user.get_full_name|default:user.username }}!</a>
                            </li>
                            <li>
                                <a href="{% url 'auth:logout' %}?next=/polls">Logout</a>
{#                                <a href="{% url 'auth:logout' %}?next={{ request.path }}">Logout</a>#}
                            </li>
                        </ul>
                    {% else %}
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="Login or Signup">Login <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="{% url 'social:begin' 'facebook' %}?next=/polls">Login with Facebook</a>
                                </li>
                                <li>
                                    <a href="{% url 'social:begin' 'google-oauth2' %}?next=/polls">Login with Google</a>
                                </li>
                                <li>
                                    <a href="{% url 'social:begin' 'twitter' %}?next=/polls">Login with Twitter</a>
                                </li>
                            </ul>
                    {% endif %}
                    </li>
                </ul>
            </div>
        </div>
	</nav>
	<!-- End navbar -->

    <div class="main-content">
        <header id="title">
            <p>UPLOAD YOUR PICTURES</p>
        </header>

        {% block main %}{% endblock %}
    </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="../../static/photos/js/jquery-1.11.1.min.js"></script>
    {#   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>#}
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="../../static/photos/js/bootstrap.min.js"></script>
</body>
</html>

mysite/photos/templates/photos/listfiles.html
{% extends 'photos/base.html' %}

{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'photos/style.css' %}" />

{% block main %}

<section class="desc">
    <p>Photo Gallery</p>
</section>

{% for name in names %}
    <img id="photos" src="{{ MEDIA_URL }}{{ name }}" scale="0.7"/>
{% endfor %}

<section class="desc" id="links">
    <p>Start over!</p>
    <a href="{% url 'photos:uploadphoto' %}">Upload a new photo</a>
</section>

{% endblock %}

mysite/photos/templates/photos/upload.html
{% extends 'photos/base.html' %}

{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'photos/style.css' %}" />

{% block main %}

<section class="desc">
    <p>A Django photo uploader app.</p>
    <p>Upload your photos and see them on your screen!</p>
</section>
<section class="forms">
    <form id="form" action="." method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <input class="buttons" type="submit" name="upload" value="upload">
    </form>
</section>

{% endblock %}