mysite/mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'mysite.views.home', name='home'),
    url(r'^contact/', 'contact.views.contact', name='contact'),
    url(r'^photos/', include('photos.urls', namespace='photos')),
    url(r'^polls/', include('polls.urls', namespace='polls')),  # namespace each app in a project
    url(r'^admin/', include(admin.site.urls)),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url('', include('django.contrib.auth.urls', namespace='auth')),
)

# The url() function is passed four arguments, two required: regex and view, and two optional: kwargs, and name.

# When somebody requests a page from your Web site - say, /polls/34/, Django will load the mysite.urls Python module
# because it is pointed to by the ROOT_URLCONF setting.
# It finds the variable named urlpatterns and traverses the regular expressions in order. 
# The include() functions we are using simply reference other URLconfs. 
# Note that the regular expressions for the include() functions do not have a $ (end-of-string match character) but
# rather a trailing slash.
# Whenever Django encounters include(), it chops off whatever part of the URL matched up to that point and sends the
# remaining string to the included URLconf for further processing.

# If a user goes to /polls/34/ in this system:
# Django will find the match at "^polls/""
# Then, Django will strip off the matching text polls/ and send the remaining text - 34/ - to the polls.urls
# URLconf for further processing which matches r"^(?P<question_id>\d+)/$"" resulting in a call to the detail() view
# like so:
# detail(request=<HttpRequest object>, question_id="34")

mysite/polls/urls.py
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'), # ex: /polls/
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'), # ex: /polls/5/
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'), # ex: /polls/5/results/
    url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'), # ex: /polls/5/vote/
    url(r'^question/', 'polls.views.get_question', name='get_question'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='auth_logout'),
    url(r'^logout/(?P<next_page>.*)/$', 'django.contrib.auth.views.logout', name='auth_logout_next'),
)

mysite/contact/models.py
from django.db import models

# Create your models here.

mysite/contact/forms.py
from django import forms


class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100, min_length=4)
    email = forms.EmailField(required=False, label='Your e-mail address')
    message = forms.CharField(widget=forms.Textarea)

    def clean_message(self):
        message = self.cleaned_data['message']
        num_words = len(message.split())
        if num_words < 4:
            raise forms.ValidationError("Not enough words! Four words or more, please.")
        return message

mysite/contact/views.py
from django.shortcuts import render
from contact.forms import ContactForm
from django.http import HttpResponseRedirect
from django.core.mail import send_mail
from django.template import RequestContext


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            send_mail(
                cd['subject'],
                cd['message'],
                cd.get('email', 'noreply@example.com'),
                ['siteowner@example.com'],
            )
            return HttpResponseRedirect('/contact/thanks/')
    else:
        form = ContactForm(
            initial={'subject': 'I love your site!'}
        )
    return render(request, 'mysite/contact_form.html', {'form': form}, context_instance=RequestContext(request))

mysite/mysite/views.py
from django.shortcuts import render_to_response
from django.template.context import RequestContext
# from django.core.mail import send_mail
# from django.http import HttpResponseRedirect
# from django.shortcuts import render


def home(request):
    context = RequestContext(request,
                           {'request': request,
                            'user': request.user})
    return render_to_response('../templates/mysite/home.html',
                             context_instance=context)


# def contact(request):
#     errors = []
#     if request.method == 'POST':
#         if not request.POST.get('subject', ''):
#             errors.append('Enter a subject.')
#         if not request.POST.get('message', ''):
#             errors.append('Enter a message.')
#         if request.POST.get('email') and '@' not in request.POST['email']:
#             errors.append('Enter a valid e-mail address.')
#         if not errors:
#             send_mail(
#                 request.POST['subject'],
#                 request.POST['message'],
#                 request.POST.get('email', 'noreply@example.com'),
#                 ['siteowner@example.com'],
#             )
#             return HttpResponseRedirect('/contact/thanks/')
#     return render(request, 'mysite/contact_form.html', {
#         'errors': errors,
#         'subject': request.POST.get('subject', ''),
#         'message': request.POST.get('message', ''),
#         'email': request.POST.get('email', ''),
#     })

mysite/mysite/templates/mysite/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Mysite With Authentication{% endblock %}</title>

    <!-- Bootstrap -->
    <link href="../../static/css/bootstrap.min.css" rel="stylesheet">
    <link href="../../static/css/bootstrap-theme.min.css" rel="stylesheet">
    {#   <link href="static/css/fbposter.css" rel="stylesheet">#}

    <link href="../../static/css/style.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,800,700,300' rel='stylesheet' type='text/css'>
    <link rel="icon" type="image/png" href="../../static/img/favicon.png">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
     <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
     <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <!-- Navbar -->
	<div class="navbar navbar-default navbar-fixed-top">
	    <div class="container">
	        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
	        </button>
            <a class="navbar-brand text-muted" href="/" title="Return home">My Site Home</a>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    {% if kwargs.page = "Create_Listing": <li id="navHome" class="active"><a href="/" title="Return home">Home</a></li> %}

                    <li id="navHome"><a href="/" title="Return home">Home</a></li>
                    <li id="navPolls"><a href="/polls" title="Check out our polls">Polls</a></li>
                    <li class="dropdown" id="navPhotos">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="Check out our photos uploader">Photos <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="/photos/uploadfile">Upload Photo</a></li>
                            <li><a href="/photos/listfiles">List Files</a></li>
                        </ul>
                    </li>
                    <li id="navContact"><a href="/contact" title="Contact us">Contact</a></li>
                    <li class="dropdown">
                    {% if user and not user.is_anonymous %}
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="Account">{{ user.username }} <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a>Hello {{ user.get_full_name|default:user.username }}!</a>
                            </li>
                            <li>
                                <a href="{% url 'auth:logout' %}?next={{ request.path }}">Logout</a>
                            </li>
                        </ul>
                    {% else %}
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="Login or Signup">Login <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}">Login with Facebook</a>
                                </li>
                                <li>
                                    <a href="{% url 'social:begin' 'google-oauth2' %}?next={{ request.path }}">Login with Google</a>
                                </li>
                                <li>
                                    <a href="{% url 'social:begin' 'twitter' %}?next={{ request.path }}">Login with Twitter</a>
                                </li>
                            </ul>
                    {% endif %}
                    </li>
                </ul>
            </div>
        </div>
	</div>
	<!-- End navbar -->

    <!-- Main content -->
    <div class="main-content">
        {% block main %}{% endblock %}
    </div>
    <!-- End main content -->
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="../../static/js/jquery-1.11.1.min.js"></script>
    {#   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>#}
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="../../static/js/bootstrap.min.js"></script>
</body>
</html>

mysite/mysite/templates/mysite/contact_form.html
<head>
    <title>Contact us</title>
</head>

{% extends 'mysite/home.html' %}

{% block main %}
    <h1>Contact Us</h1>
    <h2>We'd love to hear from you!</h2>

    {% if form.errors %}
        <p style="color: red; font-size: 16px">
            <strong>Please correct the error{{ form.errors|pluralize }} below.</strong>
        </p>
    {% endif %}

    <form action="" method="post">{% csrf_token %}
        <div class="field{% if form.subject.errors %} errors{% endif %}">
            {% if form.subject.errors %}
                <ul>
                {% for error in form.subject.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
                </ul>
            {% endif %}
            <label for="id_subject">Subject:</label>
            {{ form.subject }}
        </div>
        <div class="field{% if form.email.errors %} errors{% endif %}">
            {% if form.email.errors %}
                <ul>
                {% for error in form.email.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
                </ul>
            {% endif %}
            <label for="id_email">Your e-mail address:</label>
            {{ form.email }}
        </div>
        <div class="field{% if form.message.errors %} errors{% endif %}">
            {% if form.message.errors %}
                <ul>
                {% for error in form.message.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
                </ul>
            {% endif %}
            <label for="id_message">Message:</label>
            {{ form.message }}
        </div>
        <input type="submit" value="Submit" class="btn btn-default">
    </form>

<!-- {#    <form action="" method="post">{% csrf_token %}#}
{#        <div class="field">#}
{#            {{ form.subject.errors }}#}
{#            <label for="id_subject">Subject:</label>#}
{#            {{ form.subject }}#}
{#        </div>#}
{#        <div class="field">#}
{#            {{ form.email.errors }}#}
{#            <label for="id_email">Your e-mail address:</label>#}
{#            {{ form.email }}#}
{#        </div>#}
{#        <div class="field">#}
{#            {{ form.message.errors }}#}
{#            <label for="id_message">Message:</label>#}
{#            {{ form.message }}#}
{#        </div>#}
{#    </form>#} -->

{% endblock %}

mysite/mysite/templates/mysite/home.html
<head>
    <title>My Site Home</title>
</head>

{% extends 'mysite/base.html' %}

{% block main %}

    <h1>My Site with Authentication</h1>
    <p>Welcome!</p>

{% endblock %}